language: objective-c
osx_image: xcode7.3
sudo: required
before_install:
- ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)"
install:
- sudo easy_install pip
- sudo pip install ansible
script:
- sudo make install
- make test